global:
  namespace: vault 
server:
  dev:
    enabled: false 
  ingress:
    enabled: true 
    ingressClassName: nginx
    hosts:
    - host: vault.devsecops.tolu
  dataStorage:
    enabled: true
    # Size of the PVC created
    size: 10Gi
    # Location where the PVC will be mounted.
    mountPath: "/vault/data"
    # Name of the storage class to use.  If null it will use the
    # configured default Storage Class.
    storageClass: null
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce
    # Annotations to apply to the PVC
    annotations: {}
    # Labels to apply to the PVC
    labels: {}

injector:
  enabled: true 
csi:
  enabled: false 
